### ISSUE TITLE
Build with less memory

### ISSUE THREAD

**Issue by nandiheath** [kintoproj/kinto-core#17]
**Is your feature request related to a problem? Please describe.**
I have created a kubernetes cluster with 2 nodes, each with 2vCPU + 2GB memory.
the cluster is able to debug, and I can access the dashboard.
However when I try to build a service, it got hanged at the `PENDING` state forever. 
After investigation, the workflow pods cannot be started and remains at `unscheduled` state.
It remains the same after I added another 2GB node to the cluster, but got resolved after I add a new 4GB node to the node-pool.

Suspect that the build workflow request more than 2GB of memory.

**Describe the solution you'd like**
able to build with less memory, especially with smaller node type. 
Would be nice if the memory required for the build workflow is configurable.

**Comment by bakayolo** [comment]
Oups -> https://github.com/kintoproj/kinto-builder/blob/main/kinto-build/internal/build/argo/templates.go#L131-L135

> Would be nice if the memory required for the build workflow is configurable.

fully agreed
