### ISSUE TITLE
Support Containerd on kubernetes node 

### ISSUE THREAD

**Issue by nandiheath** [kintoproj/kinto-core#18]
**Is your feature request related to a problem? Please describe.**

When created a K8S cluster on GKE, with picking `Containerd` as the image type of the node,
after creating the Kintohub instance, it fails when creating a service.

The service deployed with `FAILED` state, however if you check on k8s the pods are running.

This is the error on argo
```
failed to save outputs: Error response from daemon: No such container: bb61bf6d5c99212c6b1941f8439461520e8d4e84219fb766ff82409f1c7f1a17
```

this may be due to the reason that argo should set up for choosing the correct image runtime
https://github.com/kubeflow/pipelines/issues/1471

**Describe the solution you'd like**
Support both docker/containerd as the image runtime, as K8S will soon deprecate docker as its container runtime.
https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/

**Comment by bakayolo** [comment]
Done, closing.
